### ISSUE TITLE
Arduino be the master could work?

### ISSUE THREAD

**Issue by s1hon** [respeaker/spi_bridge#2]
Hi,
the code of the arduino example is the slave, to recieve the data from MPU.
Is there a chance could let arduino to be the master?

I mean let arduino send datas to MPU,
thanks.

**Comment by xiongyihui** [comment]
This code use MPU's GPIOs to simulate a SPI interface. The MPU is easy to generate CLOCK signal as a SPI master, but is very hard to detect CLOCK signal when as a SPI slave. So the MPU is not suitable as a slave.

Arduino as a SPI slave can also send data back to MPU. I just update the code to demonstrate it.

https://github.com/respeaker/spi_bridge/blob/master/arduino_32u4_spi_slave.ino#L39
